### ISSUE TITLE
Wrong if statement in software::scaling::context::Context

### ISSUE THREAD

**Issue by jocaml** [zmwangx/rust-ffmpeg#1]
In line 59, it should be `!ptr.is_null()`?
https://github.com/zmwangx/rust-ffmpeg/blob/e13b01f30b5da880b7c4ddb6f8f796e3a793dd52/src/software/scaling/context.rs#L46-L60

See https://www.ffmpeg.org/doxygen/3.1/group__libsws.html#gaf360d1a9e0e60f906f74d7d44f9abfdd

**Comment by zmwangx** [comment]
Thanks for the report. Fixed in a7ea073. I can't promise when I'll cut a new release though — I'll need to find time to prepare an FFmpeg 4.1 compat patch first.
