### ISSUE TITLE
Question about keeping a reference to the encoder somehow

### ISSUE THREAD

**Issue by FLamparski** [zmwangx/rust-ffmpeg#13]
I want to create an object which I can feed frames one by one for them to be encoded and written out to some output file. The frames may come from an asynchronous source so I can't keep everything within a single function call. To that end, I define a struct like this:

```rust
pub struct Encoder<'a, R: Into<Rational> + Copy + Clone> {
    request: &'a Request,
    video_info: &'a VideoInfo<R>,
    output: &'a mut OutputContext,
    scaler: ScalingContext,
    encoder: VideoEncoder,
    stream: StreamMut<'a>,
}
```

And the constructor:

```rust
    pub fn new(output: &'a mut OutputContext, request: &'a Request, video_info: &'a VideoInfo<R>) -> Result<Self, ffmpeg::Error> {
        let scaler = ScalingContext::get(/* snip */)?;

        let codec = find_codec(CodecId::H264).ok_or(ffmpeg::Error::EncoderNotFound)?;

        let mut stream = output.add_stream(codec)?;
        let mut encoder = stream.codec().encoder().video()?;
        // snip

        let encoder = encoder.open_as(codec)?;
        stream.set_parameters(&encoder);
        // snip

        Ok(Self { request, video_info, output, scaler, encoder, stream })
    }
```

To me, this looks fairly sane, however the borrow checker complains that `output` ends up being mutably borrowed twice:

```
error[E0499]: cannot borrow `*output` as mutable more than once at a time
  --> src\encoder.rs:53:40
   |
28 | impl<'a, R> Encoder<'a, R>
   |      -- lifetime `'a` defined here
...
42 |         let mut stream = output.add_stream(codec)?;
   |                          ------------------------
   |                          |
   |                          first mutable borrow occurs here
   |                          argument requires that `*output` is borrowed for `'a`
...
53 |         Ok(Self { request, video_info, output, scaler, encoder, stream })
   |                                        ^^^^^^ second mutable borrow occurs here
```

What would be the best way of going around this?

**Comment by FLamparski** [comment]
I should add, ideally I would also like to create the `OutputContext` inside the constructor itself, however if I do that, Rust then claims that it does not live long enough for `'a`. For now I am okay with just passing it in externally, though.

**Comment by abhijeetbhagat** [comment]
If you create an `OutputContext` inside the constructor, then its lifetime will be valid only till the constructor scope end and not `'a`. You can just change `output`'s type from `&'a mut OutputContext` to `OutputContext` to indicate that `Encoder` takes ownership of an `OutputContext`.

**Comment by zmwangx** [comment]
Huh, seems I somehow completely ignored this question... Sorry. Closing due to age.
