### ISSUE TITLE
Work with other formats

### ISSUE THREAD

**Issue by Pablo-163** [zmwangx/rust-ffmpeg#17]
Hello! I try to decode some videos encoded by H264. And i faced some troubles. Well, when i try to decode example.mp4 and example.avi  I get errors "no frame!" or "Invalid NAL unit size 21274662>141". So how can I fix it? What should I do for reading other containers?
P.S. i use code like "avi to ppm"
![Снимок экрана от 2020-07-22 09-23-15](https://user-images.githubusercontent.com/68630324/88137664-17855580-cbfd-11ea-8629-1b113f7c59d0.png)
![Снимок экрана от 2020-07-22 09-22-50](https://user-images.githubusercontent.com/68630324/88137669-19e7af80-cbfd-11ea-8589-4e9bd820be70.png)

**Comment by zmwangx** [comment]
Better supply the actual code you're using and the sample files, otherwise it's just a guessing game as to what you did wrong.

**Comment by Pablo-163** [comment]
you are right . well, I commented my lines and use original  "avi to ppm" example and that problem still exist. i used these videos:
[examples.zip](https://github.com/zmwangx/rust-ffmpeg/files/4959842/examples.zip)

**Comment by zmwangx** [comment]
Okay, the example `avi-to-ppm` was only expecting a single stream in the input file, as it attempts to decode every single packet with the same decoder: https://github.com/zmwangx/rust-ffmpeg/blob/5d74df996d3927c03791cfa888b45b0dab3e07a2/examples/avi-to-ppm.rs#L34.

As such

```console
$ ffmpeg -i example.avi -c:v copy -an example-video-only.avi
$ cargo run --example avi-to-ppm example.avi
```

should work just fine.

I've made it more tolerant in 3e9c83ec4e915139d0d0435463f007e7b7667cdb, which should work with your sample files just fine. Let me know if there are additional problems.

**Comment by Pablo-163** [comment]
Thanks! It is work. But what the another stream in these files? These videos hasn't sound streams. 
P.S. Sorry for the trouble!  i am new at video-processing

**Comment by zmwangx** [comment]
```console
$ ffprobe /tmp/example.avi
Input #0, avi, from '/tmp/example.avi':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 00:00:20.27, start: 0.000000, bitrate: 840 kb/s
    Stream #0:0: Video: h264 (High) (H264 / 0x34363248), yuv420p(progressive), 1152x720 [SAR 1:1 DAR 8:5], 697 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 44100 Hz, stereo, fltp, 128 kb/s
```

Your sample videos appear to be silent, but they do have sound streams.

Closing the issue since it appears resolved. Feel free to ask questions though.

**Comment by zmwangx** [comment]
Btw, a tip (condescension not intended): to use rust-ffmpeg it's best to familiarize yourself with FFmpeg first. The command line programs would be the first step.

**Comment by Pablo-163** [comment]
Ok. Thanks a lot!
