### ISSUE TITLE
docs.rs failed to build ffmpeg-next-0.2.0

### ISSUE THREAD

**Issue by ohmyarch** [zmwangx/rust-ffmpeg#2]

**Comment by zmwangx** [comment]
An appropriate version of libav* needs to be present to build the docs. I don’t think docs.rs’ build server has it, and I didn’t bother to contact docs.rs’ owner.

**Comment by zmwangx** [comment]
This should be fixed by https://github.com/rust-lang/crates-build-env/pull/45.

**Comment by jyn514** [comment]
I queued a rebuild of 4.2.1 (https://docs.rs/releases/queue), let me know if that doesn't fix the issue.

**Comment by zmwangx** [comment]
Thanks!

**Comment by zmwangx** [comment]
https://docs.rs/ffmpeg-next/4.2.1/ffmpeg_next/
