### ISSUE TITLE
An error occurred when building on window

### ISSUE THREAD

**Issue by 238-699** [zmwangx/rust-ffmpeg#220]
error: failed to run custom build command for `ffmpeg-sys-next v7.1.0`

Caused by:
  process didn't exit successfully: `D:\projects\tauri-chat\src-tauri\target\debug\build\ffmpeg-sys-next-3680791a0c1441e7\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-search=native=E:\tool\ffmpeg-7.1-full_build-shared\lib
  cargo:rustc-link-lib=dylib=avutil
  OPT_LEVEL = Some(0)
  OUT_DIR = Some(D:\projects\tauri-chat\src-tauri\target\debug\build\ffmpeg-sys-next-860d47f914aa53c6\out)
  cargo:rerun-if-env-changed=VCINSTALLDIR
  VCINSTALLDIR = None
  cargo:rerun-if-env-changed=VSTEL_MSBuildProjectFullPath
  VSTEL_MSBuildProjectFullPath = None
  cargo:rerun-if-env-changed=VSCMD_ARG_VCVARS_SPECTRE
  VSCMD_ARG_VCVARS_SPECTRE = None
  cargo:rerun-if-env-changed=WindowsSdkDir
  WindowsSdkDir = None
  cargo:rerun-if-env-changed=WindowsSDKVersion
  WindowsSDKVersion = None
  cargo:rerun-if-env-changed=LIB
  LIB = None
  PATH = Some(D:\projects\tauri-chat\src-tauri\target\debug\deps;D:\projects\tauri-chat\src-tauri\target\debug;C:\Users\admin\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Users\admin\anaconda3\condabin;C:\Python312\Scripts\;C:\Python312\;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp;E:\tool\Java\LibericaJDK-21\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\ComposerSetup\bin;E:\tool\Git\cmd;C:\msys64\mingw64\bin;E:\tool\make-4.4\GccRel;E:\tool\ffmpeg-7.1-full_build-shared\bin;E:\tool\Tencent\微信web开发者工具\dll;E:\tool\Microsoft VS Code\bin;C:\Program Files (x86)\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\cudnn\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\extras\CUPTI\lib64;E:\tool\Xshell 8\;E:\tool\apache-maven-3.9.6\bin;C:\Program Files\Docker\Docker\resources\bin;E:\tool\gradle-8.7\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.3.0\;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files (x86)\NetSarang\Xftp 8\;C:\Users\admin\AppData\Roaming\npm;E:\tool\protoc-27.1-win64\bin;C:\Users\admin\anaconda3;C:\Users\admin\anaconda3\Scripts;C:\Users\admin\projects\emsdk;C:\Users\admin\projects\emsdk\upstream\emscripten;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;E:\tool\php\php-8.3.9-nts;C:\Program Files (x86)\NetSarang\Xmanager 7\;C:\Users\admin\AppData\Roaming\Python\Python311\Scripts;C:\Users\admin\pipx\venvs\poetry\Scripts;C:\Program Files\CMake\bin;C:\Users\admin\AppData\Local\bin\NASM;C:\Program Files (x86)\NetSarang\Xmanager 8\;C:\Program Files\OpenSSL-Win64\bin;E:\tool\Go\bin;E:\Android\Sdk\platform-tools;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64;D:\projects\vcpkg;E:\tool\nodejs\v23.1.0\;C:\ProgramData\chocolatey\bin;C:\Users\admin\.cargo\bin;C:\Users\admin\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\admin\AppData\Local\Programs\Python\Python311\;C:\Users\admin\AppData\Local\pnpm;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Roaming\Composer\vendor\bin;E:\tool\Microsoft VS Code\bin;E:\tool\Fiddler;C:\Users\admin\.dotnet\tools;c:\users\admin\.local\bin;C:\Users\admin\go\bin;C:\Users\admin\AppData\Roaming\npm)
  cargo:rerun-if-env-changed=INCLUDE
  INCLUDE = None
  HOST = Some(x86_64-pc-windows-msvc)
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some(cmpxchg16b,fxsr,sse,sse2,sse3)
  DEBUG = Some(true)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  check.c
  E:\tool\ffmpeg-7.1-full_build-shared\include\libavutil\common.h(213): warning C4244: “return”: 从“int”转换到“uint8_t”，可能丢失数据
  E:\tool\ffmpeg-7.1-full_build-shared\include\libavutil\common.h(224): warning C4244: “return”: 从“int”转换到“int8_t”，可能丢失数据
  E:\tool\ffmpeg-7.1-full_build-shared\include\libavutil\common.h(235): warning C4244: “return”: 从“int”转换到“uint16_t”，可能丢失数据
  E:\tool\ffmpeg-7.1-full_build-shared\include\libavutil\common.h(246): warning C4244: “return”: 从“int”转换到“int16_t”，可能丢失数据
  E:\tool\ffmpeg-7.1-full_build-shared\include\libavutil\rational.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
  check.c(198): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(198): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(198): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(199): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(199): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(199): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(200): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(200): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(200): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(201): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(201): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(201): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(202): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(202): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(202): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(203): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(203): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(203): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(204): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(204): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(204): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(205): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(205): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(205): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(206): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(206): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(206): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(207): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(207): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(207): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(208): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(208): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(208): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(209): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(209): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(209): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(210): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(210): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(210): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(211): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(211): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(211): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(212): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(212): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(212): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(213): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(213): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(213): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(214): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(214): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(214): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(215): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(215): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(215): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(216): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(216): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(216): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(217): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(217): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(217): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(218): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(218): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(218): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(219): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(219): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(219): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(220): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(220): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(220): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(221): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(221): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(221): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(222): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(222): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(222): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(223): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(223): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(223): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(224): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(224): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(224): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(225): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(225): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(225): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(226): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(226): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(226): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(227): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(227): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(227): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(228): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(228): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(228): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(229): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(229): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(229): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(230): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(230): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(230): error C2065: “LIBAVCODEC_VERSION_MINOR”: 未声明的标识符
  check.c(231): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(231): error C2065: “LIBAVCODEC_VERSION_MAJOR”: 未声明的标识符
  check.c(231): fatal error C1003: 错误计数超过 100；正在停止编译

  --- stderr
  cl: 命令行 warning D9035 :“o”选项已否决，并将在将来的版本中移除
  thread 'main' panicked at C:\Users\admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ffmpeg-sys-next-7.1.0\build.rs:520:9:
  Compile failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

Does anyone know how to solve this?
Cargo.toml
ffmpeg-next = { version = "7.1.0", default-features = false }

**Comment by typed-sigterm** [comment]
Hi, I met the problem too. Do you remember how you solve this?
