### ISSUE TITLE
Decoding a byte stream, rather than a file

### ISSUE THREAD

**Issue by lukehsiao** [zmwangx/rust-ffmpeg#29]
I'm interested in using ffmpeg-next to decode an h264 bytestream. The examples focus on opening an input file and processing it to produce an output. While I can probably match this type of setup using /dev/stdout, I'd rather have a way to decode a buffer of bytes representing a h264 NAL. 

To make this more concrete, you can imagine an example which uses [x264-rs to encode a frame](https://github.com/rust-av/x264-rs/blob/master/examples/encode.rs), then I would like to use ffmpeg-next to decode those bytes with as low latency as possible. The overall goal is to have a simple program which encodes, decodes, and displays a video with as low end-to-end latency as possible (i.e., with less latency than something like `./x264 --preset fast --tune zerolatency input.y4m -o /dev/stdout | mpv --profile=low-latency -`)

Would ffmpeg-next be a good fit as the decoder for this use case?

**Comment by zmwangx** [comment]
Not sure I see the logic behind the encode -> decode -> display workflow as opposed to just display, neither can I see why you can't just use the FFmpeg wrapper end-to-end as libavcodec already wraps x264 (also, gotta say, having worked with the x264-rs repo you linked a bit, the code quality leaves something to be desired), but yes you can feed raw NAL units independent of an input file.

What you're looking for is [`Packet::copy`](https://docs.rs/ffmpeg-next/4.3.6/ffmpeg_next/codec/packet/packet/struct.Packet.html#method.copy) which bridges the gap by wrapping your NAL byte buffer into a packet libavcodec can work with. Then you just feed the packets into a decoder as usual.

I adapted the encode example you linked to into something that decodes the encoded NAL units and dumps the decoded frames as images (of course you can do anything else with the decoded frames, including displaying them): https://gist.github.com/zmwangx/0efa56bba9daef3d460b9ccf3a4832df

As for latency, you'll just have to write benchmarks.

**Comment by lukehsiao** [comment]
> Not sure I see the logic behind the encode -> decode -> display workflow as opposed to just display, neither can I see why you can't just use the FFmpeg wrapper end-to-end as libavcodec already wraps x264 (also, gotta say, having worked with the x264-rs repo you linked a bit, the code quality leaves something to be desired)

Yes, quite roundabout a know. The reason is we are actually working on changes to x264's encoder, so we want to encode and decode to see the results.

> What you're looking for is Packet::copy which bridges the gap by wrapping your NAL byte buffer into a packet libavcodec can work with. Then you just feed the packets into a decoder as usual.
>
> I adapted the encode example you linked to into something that decodes the encoded NAL units and dumps the decoded frames as images (of course you can do anything else with the decoded frames, including displaying them): https://gist.github.com/zmwangx/0efa56bba9daef3d460b9ccf3a4832df

This is amazingly helpful, thank you! I'll start from there.

**Comment by zmwangx** [comment]
> The reason is we are actually working on changes to x264's encoder, so we want to encode and decode in realtime to see the results.

That makes more sense. Good luck.
