### ISSUE TITLE
remove resampling from default features.

### ISSUE THREAD

**Issue by geovex** [zmwangx/rust-ffmpeg#3]
Since `avresample` not present in most builds.

**Comment by zmwangx** [comment]
Thanks for the suggestion. Since I'm too short on time at the moment to investigate this, could you please list which builds you have checked and which ones don't have avresample? (Kinda reluctant to deviate from the original without good reason.)

**Comment by zmwangx** [comment]
Oh, just remembered lavr was entirely deprecated since 4.0.0... So this sounds totally reasonable, will do.

**Comment by zmwangx** [comment]
It took a full year, but I finally got around to updating this project... Fixed in v4.2.1.
