### ISSUE TITLE
Encoding to bytestream

### ISSUE THREAD

**Issue by Pablo-163** [zmwangx/rust-ffmpeg#32]
Hello. I would like to receive one video-stream and transcode it to MJPEG. So I found that encoder in ffmpeg-next need someone path for output. But I don't  need to make a file, I am going to use only bytestream. Have ffmpeg-next any solutions for that ?

**Comment by Pablo-163** [comment]
So I found the one way. It's  not what I wanted to find but it also work well.

```
let out="/dev/null";
let mut octx = format::output_as(& output, & "mp4").unwrap();
```
P.S. any other format can be used.

**Comment by j-man123** [comment]
thanks for this!
