### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Joseph-LeGrice** [zmwangx/rust-ffmpeg#33]
Will you accept any documentation PR's for this library? I'm about to set off on a journey of learning ffmpeg, so I might just add documentation for the methods I use along the way if so.

**Comment by Joseph-LeGrice** [comment]
Decided to go with a different library, so offer rescinded. Sorry!

**Comment by eastrd** [comment]
Would you mind telling me which library you ended up going with?

> Decided to go with a different library, so offer rescinded. Sorry!
