### ISSUE TITLE
wasm-pack build err

### ISSUE THREAD

**Issue by niugm** [zmwangx/rust-ffmpeg#40]
HI,guys,i try to use this crate with wasm-pack,when i run wasm-pack build,i got err like below:

--- stdout
cargo:rerun-if-env-changed=LIBAVUTIL_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_wasm32-unknown-unknown
cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_wasm32_unknown_unknown
cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
cargo:rerun-if-env-changed=PKG_CONFIG_wasm32-unknown-unknown
cargo:rerun-if-env-changed=PKG_CONFIG_wasm32_unknown_unknown
cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_wasm32-unknown-unknown
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_wasm32_unknown_unknown
cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

--- stderr
thread 'main' panicked at 'called Result::unwrap() on an Err value: CrossCompilation', /Users/niugm/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-next-4.3.5/build.rs:700:14
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute cargo build: exited with exit code: 101
full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"

**Comment by zmwangx** [comment]
I expect a lot of work supporting wasm as a target when there’s a big C dependency (in fact not just C, there’s C++ too, and even Rust in the form of rav1e). I have little experience in that regard so the work won’t be coming from me. If someone’s willing to take up that work, I’m open to merging it. Anyone who would like to use FFmpeg in a wasm context but don’t want to put in the work might find more success with an existing wasm port of FFmpeg, e.g. https://ffmpegwasm.github.io/.

**Comment by niugm** [comment]
> I expect a lot of work supporting wasm as a target when there’s a big C dependency (in fact not just C, there’s C++ too, and even Rust in the form of rav1e). I have little experience in that regard so the work won’t be coming from me. If someone’s willing to take up that work, I’m open to merging it. Anyone who would like to use FFmpeg in a wasm context but don’t want to put in the work might find more success with an existing wasm port of FFmpeg, e.g. https://ffmpegwasm.github.io/.

Thanks for the reply
