### ISSUE TITLE
Finding the best stream for media type seems broken

### ISSUE THREAD

**Issue by msairio** [zmwangx/rust-ffmpeg#97]
This change (https://github.com/zmwangx/rust-ffmpeg/commit/22ad8b959879efa028c33f71cc286b519eae8066#diff-69c1251ae6ce669cc79c6e50c4bb725dee4e6deaf6ca8778fb2e58a61bce2ceaR169-R175) seems to be broken. The decoder is null regardless of whether av_find_best_stream finds a suitable stream or not and the best function returns always None. This can be reproduced with the example https://github.com/zmwangx/rust-ffmpeg/blob/master/examples/dump-frames.rs which no longer finds streams nor dumps any frames. 

Revering the change back, i.e. making decoder mutable, seems to fix the issue.

**Comment by Polochon-street** [comment]
Hi,

Someone submitted https://github.com/zmwangx/rust-ffmpeg/pull/95 that fixes it :). I just merged the PR.

**Comment by shssoichiro** [comment]
Would it be possible to publish a new version of this crate which contains this fix? I have a crate I'd like to publish a new version of, but is currently linked to the git master of this crate.

**Comment by Polochon-street** [comment]
Should be published now :) Closing the issue.
